export {
    getSkillsPage,
    getEducationPage,
    getProjectsPage,
    getContactsPage,
    getExperiencePage,
    getAboutPage,
    getNavbarData,
    getHubPage,
    getHubEntries,
    getHubEntriesByCategory,
    getHubEntryBySlug,
    getHubEntrySlugs,
    getHubCategories,
    getHubCategoryBySlug,
    getHubCategorySlugs,
} from './Sanity';